-- Repeatable: re-applied whenever its checksum changes, since the category/topic list is
-- reference data rather than user data. See docs/domain-model.md#migration-plan.
insert into category (slug, name, icon_url, display_order) values
    ('arts-culture',         'Arts & Culture',         null, 1),
    ('book-clubs',           'Book Clubs',             null, 2),
    ('career-business',      'Career & Business',      null, 3),
    ('dance',                'Dance',                  null, 4),
    ('education',            'Education & Learning',   null, 5),
    ('fashion-beauty',       'Fashion & Beauty',       null, 6),
    ('fitness',              'Fitness',                null, 7),
    ('food-drink',           'Food & Drink',           null, 8),
    ('games',                'Games',                  null, 9),
    ('health-wellbeing',     'Health & Wellbeing',     null, 10),
    ('hobbies-crafts',       'Hobbies & Crafts',       null, 11),
    ('identity-language',    'Identity & Language',    null, 12),
    ('lgbtq',                'LGBTQ+',                 null, 13),
    ('movements-politics',   'Movements & Politics',   null, 14),
    ('music',                'Music',                  null, 15),
    ('outdoors-adventure',   'Outdoors & Adventure',   null, 16),
    ('parents-family',       'Parents & Family',       null, 17),
    ('pets-animals',         'Pets & Animals',         null, 18),
    ('photography',          'Photography',            null, 19),
    ('religion-spirituality','Religion & Spirituality',null, 20),
    ('sci-fi-fantasy',       'Sci-Fi & Fantasy',       null, 21),
    ('social-activities',    'Social Activities',      null, 22),
    ('sports',               'Sports',                 null, 23),
    ('tech',                 'Technology',             null, 24)
on conflict (slug) do update set
    name = excluded.name,
    icon_url = excluded.icon_url,
    display_order = excluded.display_order;

insert into topic (category_id, slug, name)
select c.id, t.slug, t.name
from (values
    ('arts-culture',          'painting',          'Painting'),
    ('arts-culture',          'theater',           'Theater'),
    ('book-clubs',            'fiction',           'Fiction'),
    ('book-clubs',            'nonfiction',        'Non-fiction'),
    ('career-business',       'entrepreneurship',  'Entrepreneurship'),
    ('career-business',       'networking',        'Professional Networking'),
    ('dance',                 'salsa',             'Salsa'),
    ('dance',                 'ballroom',          'Ballroom'),
    ('education',             'language-exchange', 'Language Exchange'),
    ('education',             'public-speaking',   'Public Speaking'),
    ('fashion-beauty',        'streetwear',        'Streetwear'),
    ('fashion-beauty',        'skincare',          'Skincare'),
    ('fitness',               'running',           'Running'),
    ('fitness',               'yoga',              'Yoga'),
    ('food-drink',            'wine-tasting',      'Wine Tasting'),
    ('food-drink',            'home-cooking',      'Home Cooking'),
    ('games',                 'board-games',       'Board Games'),
    ('games',                 'video-games',       'Video Games'),
    ('health-wellbeing',      'mental-health',     'Mental Health'),
    ('health-wellbeing',      'meditation',        'Meditation'),
    ('hobbies-crafts',        'knitting',          'Knitting'),
    ('hobbies-crafts',        'woodworking',       'Woodworking'),
    ('identity-language',     'expats',            'Expats'),
    ('identity-language',     'polyglots',         'Polyglots'),
    ('lgbtq',                 'lgbtq-social',      'LGBTQ+ Social'),
    ('lgbtq',                 'lgbtq-support',     'LGBTQ+ Support'),
    ('movements-politics',    'volunteering',      'Volunteering'),
    ('movements-politics',    'climate-action',    'Climate Action'),
    ('music',                 'live-music',        'Live Music'),
    ('music',                 'songwriting',       'Songwriting'),
    ('outdoors-adventure',    'hiking',            'Hiking'),
    ('outdoors-adventure',    'camping',           'Camping'),
    ('parents-family',        'new-parents',       'New Parents'),
    ('parents-family',        'family-outings',    'Family Outings'),
    ('pets-animals',          'dog-walking',       'Dog Walking'),
    ('pets-animals',          'animal-rescue',     'Animal Rescue'),
    ('photography',           'street-photography','Street Photography'),
    ('photography',           'portrait',          'Portrait'),
    ('religion-spirituality', 'meditation-practice','Meditation Practice'),
    ('religion-spirituality', 'bible-study',       'Bible Study'),
    ('sci-fi-fantasy',        'tabletop-rpg',      'Tabletop RPG'),
    ('sci-fi-fantasy',        'fan-fiction',       'Fan Fiction'),
    ('social-activities',     'happy-hour',        'Happy Hour'),
    ('social-activities',     'new-in-town',       'New in Town'),
    ('sports',                'pickup-soccer',     'Pickup Soccer'),
    ('sports',                'cycling',           'Cycling'),
    ('tech',                  'web-development',   'Web Development'),
    ('tech',                  'artificial-intelligence', 'Artificial Intelligence')
) as t(category_slug, slug, name)
join category c on c.slug = t.category_slug
on conflict (slug) do update set
    name = excluded.name,
    category_id = excluded.category_id;
